'use client'
import {
  Wifi, Utensils, Wind, Ban, Waves, Dumbbell, Sparkles, Car, Shirt, Bell,
  ConciergeBell, Briefcase, Bus, Baby, Umbrella, Tv, Coffee, Lock,
  Refrigerator, DoorOpen, ArrowUpDown, Accessibility, Martini, Plane,
  Speaker, Bath, Map, Users, CreditCard, Building, Activity, Trees,
  CloudSun, Laptop, Luggage, Clock, Thermometer, Snowflake, VolumeX,
  Key, Armchair, ShowerHead, CigaretteOff, MapPin,
  // Tours & Adventures
  Mountain, Compass, Tent, Flame, Camera, Binoculars, Footprints,
  Flag, Globe, Sunrise, Sunset, Star, Heart, Shield, Zap,
  Navigation, Route, Timer, Calendar, Sun, Moon, CloudRain,
  Backpack, Flashlight, TreePine, Fish, Anchor, Sailboat,
  // Cabs & Transport
  CarFront, Fuel, Gauge, CircleParking, SquareParking, Phone, MessageSquare,
  Receipt, Banknote, Smartphone, Navigation2, MapPinned,
  CircleDot, Radio, Plug, BatteryCharging, Settings, Wrench,
  // Bikes
  Bike, CircleGauge, AlertTriangle, CheckCircle, Award, Crown, Gem,
  Eye, Headphones, Music, Volume2, Power, RotateCw, RefreshCw,
  Package, Box, Truck, Send, Download, Upload, Share2,
  // General / Safety
  ShieldCheck, ShieldAlert, LifeBuoy, Siren, Cross, Stethoscope,
  HandMetal, ThumbsUp, BadgeCheck, Info, HelpCircle, BookOpen,
  Scissors, PenTool, Palette, Paintbrush, Image, Video,
  Milestone, SignpostBig, LandPlot, Waypoints, TentTree,
  Droplets,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const FoodAndDrinks: Record<string, LucideIcon> = {
  breakfast: Coffee,
  restaurant: Utensils,
  bar: Martini,
  coffee: Coffee,
  room_service: Bell,
  minibar: Refrigerator,
  kitchen: Utensils,
  kitchenette: Utensils,
  dining: Utensils,
  buffet: Utensils,
  snack_bar: Coffee,
  tea: Coffee,
};

export const ConnectivityAndBusiness: Record<string, LucideIcon> = {
  wifi: Wifi,
  free_wifi: Wifi,
  business_center: Briefcase,
  meeting_rooms: Users,
  workspace: Laptop,
  desk: Laptop,
  conference_room: Users,
  printer: Laptop,
  fax: Laptop,
};

export const ComfortAndClimate: Record<string, LucideIcon> = {
  ac: Snowflake,
  air_conditioning: Snowflake,
  heating: Thermometer,
  soundproof_rooms: VolumeX,
  fan: Wind,
  climate_control: Thermometer,
};

export const RulesAndAccess: Record<string, LucideIcon> = {
  no_smoking: Ban,
  non_smoking_rooms: CigaretteOff,
  pets_allowed: Activity,
  wheelchair_accessible: Accessibility,
  elevator: ArrowUpDown,
  lift: ArrowUpDown,
  private_entrance: Key,
  "24_hour_front_desk": Clock,
  luggage_storage: Luggage,
  accessible: Accessibility,
};

export const Facilities: Record<string, LucideIcon> = {
  pool: Waves,
  swimming_pool: Waves,
  gym: Dumbbell,
  fitness_center: Dumbbell,
  spa: Sparkles,
  wellness_center: Sparkles,
  parking: Car,
  free_parking: Car,
  laundry: Shirt,
  daily_housekeeping: Sparkles,
  dry_cleaning: Shirt,
  concierge: ConciergeBell,
  garden: Trees,
  terrace: CloudSun,
  sauna: Flame,
  hot_tub: Droplets,
};

export const RoomFeatures: Record<string, LucideIcon> = {
  tv: Tv,
  flat_screen_tv: Tv,
  safe: Lock,
  safety_deposit_box: Lock,
  balcony: DoorOpen,
  terrace: CloudSun,
  sea_view: Waves,
  garden_view: Trees,
  city_view: Building,
  mountain_view: Mountain,
  private_bathroom: Bath,
  shower: ShowerHead,
  bath: Bath,
  sofa: Armchair,
  seating_area: Armchair,
  wardrobe_or_closet: Shirt,
  iron: Settings,
  hair_dryer: Wind,
  toiletries: Sparkles,
};

export const Locations: Record<string, LucideIcon> = {
  private_beach_area: Waves,
  waterfront: MapPin,
  beachfront: Waves,
  city_center: Building,
  near_airport: Plane,
  near_station: Bus,
};

export const onsite: Record<string, LucideIcon> = {
  private_beach_area: Waves,
  waterfront: MapPin,
  balcony: DoorOpen,
};

export const Transport: Record<string, LucideIcon> = {
  shuttle: Bus,
  airport_shuttle: Plane,
  car_rental: Car,
  taxi: Car,
  transfer: Bus,
};

export const Family: Record<string, LucideIcon> = {
  family_rooms: Baby,
  kids_club: Activity,
  babysitting: Baby,
  playground: Activity,
  children_pool: Waves,
};


export const TourFeatures: Record<string, LucideIcon> = {
  guided_tour: Flag,
  local_guide: Users,
  group_tour: Users,
  private_tour: Key,
  walking_tour: Footprints,
  city_tour: Building,
  cultural_tour: Globe,
  historical_tour: BookOpen,
  food_tour: Utensils,
  photography_tour: Camera,
  sightseeing: Binoculars,
  scenic_views: Eye,
  sunrise_tour: Sunrise,
  sunset_tour: Sunset,
  night_tour: Moon,
  day_trip: Sun,
  multi_day_tour: Calendar,
  flexible_itinerary: Route,
  fixed_itinerary: Milestone,
  luxury_tour: Crown,
  budget_tour: Banknote,
  eco_tour: TreePine,
  wildlife_tour: Fish,
  boat_tour: Sailboat,
  bus_tour: Bus,
  adventure_tour: Mountain,
  heritage_walk: Footprints,
  temple_tour: Building,
  island_hopping: Anchor,
  desert_safari: Sun,
};

export const TourAmenities: Record<string, LucideIcon> = {
  transport_included: Bus,
  meals_included: Utensils,
  breakfast_included: Coffee,
  lunch_included: Utensils,
  dinner_included: Utensils,
  hotel_pickup: Car,
  hotel_dropoff: Car,
  entrance_fees: CreditCard,
  travel_insurance: Shield,
  first_aid: Cross,
  water_bottle: Droplets,
  snacks: Coffee,
  audio_guide: Headphones,
  map_provided: Map,
  wifi_on_bus: Wifi,
  air_conditioned_vehicle: Snowflake,
  professional_photographer: Camera,
  souvenir: Package,
  certificate: Award,
  free_cancellation: RefreshCw,
  instant_confirmation: CheckCircle,
  mobile_ticket: Smartphone,
  wheelchair_accessible: Accessibility,
  pet_friendly: Activity,
  child_friendly: Baby,
  luggage_storage: Luggage,
  multilingual_guide: Globe,
  live_commentary: Speaker,
  emergency_support: Phone,
  restroom_stops: DoorOpen,
};


export const AdventureFeatures: Record<string, LucideIcon> = {
  trekking: Mountain,
  hiking: Footprints,
  camping: Tent,
  rock_climbing: Mountain,
  bungee_jumping: Zap,
  zip_lining: Zap,
  paragliding: Wind,
  skydiving: Plane,
  scuba_diving: Waves,
  snorkeling: Waves,
  surfing: Waves,
  kayaking: Sailboat,
  rafting: Waves,
  white_water_rafting: Waves,
  mountain_biking: Bike,
  trail_running: Footprints,
  canyoning: Mountain,
  rappelling: Mountain,
  wildlife_safari: Binoculars,
  jungle_trek: TreePine,
  desert_trek: Sun,
  snow_trek: Snowflake,
  ice_climbing: Snowflake,
  skiing: Mountain,
  snowboarding: Mountain,
  horse_riding: Navigation,
  atv_ride: CarFront,
  off_roading: CarFront,
  bonfire: Flame,
  stargazing: Star,
  fishing: Fish,
  river_crossing: Waves,
  waterfall_visit: Droplets,
  cave_exploration: Flashlight,
  night_camping: Moon,
  sunrise_hike: Sunrise,
  sunset_viewpoint: Sunset,
  bird_watching: Binoculars,
  nature_walk: TreePine,
  volcano_hike: Flame,
};

export const AdventureAmenities: Record<string, LucideIcon> = {
  safety_gear: Shield,
  helmet: ShieldCheck,
  harness: Shield,
  life_jacket: LifeBuoy,
  safety_briefing: Info,
  trained_instructor: Users,
  certified_guide: BadgeCheck,
  emergency_kit: Cross,
  first_aid_kit: Cross,
  walkie_talkie: Radio,
  camping_gear: Tent,
  sleeping_bag: Package,
  tent_provided: Tent,
  backpack_provided: Backpack,
  trekking_poles: Footprints,
  flashlight: Flashlight,
  meals_included: Utensils,
  campfire_dinner: Flame,
  drinking_water: Droplets,
  energy_snacks: Coffee,
  transport_included: Bus,
  pickup_dropoff: Car,
  parking_available: CircleParking,
  travel_insurance: Shield,
  medical_support: Stethoscope,
  photo_service: Camera,
  gopro_rental: Video,
  difficulty_easy: ThumbsUp,
  difficulty_moderate: Activity,
  difficulty_hard: Zap,
  age_restriction: AlertTriangle,
  weather_dependent: CloudRain,
  rain_gear: Umbrella,
  sun_protection: Sun,
  group_discount: Users,
  solo_friendly: Heart,
  couple_friendly: Heart,
  family_friendly: Baby,
  pet_allowed: Activity,
  eco_friendly: TreePine,
  leave_no_trace: TreePine,
};

export const CabFeatures: Record<string, LucideIcon> = {
  sedan: CarFront,
  suv: CarFront,
  hatchback: CarFront,
  luxury_car: Crown,
  premium_car: Gem,
  economy_car: Car,
  electric_car: BatteryCharging,
  hybrid_car: Plug,
  ac_cab: Snowflake,
  non_ac_cab: Wind,
  automatic: Settings,
  manual: Settings,
  one_way: Navigation2,
  round_trip: RotateCw,
  outstation: Route,
  local: MapPinned,
  airport_transfer: Plane,
  railway_transfer: Bus,
  hourly_rental: Clock,
  daily_rental: Calendar,
  shared_cab: Users,
  private_cab: Key,
  carpooling: Users,
  chauffeur_driven: Users,
  self_drive: Car,
  intercity: Route,
  intracity: MapPinned,
  night_service: Moon,
  early_morning: Sunrise,
};

export const CabAmenities: Record<string, LucideIcon> = {
  air_conditioning: Snowflake,
  music_system: Music,
  bluetooth: Radio,
  usb_charging: Plug,
  phone_charger: BatteryCharging,
  wifi: Wifi,
  gps_navigation: Navigation,
  gps_tracking: Navigation2,
  baby_seat: Baby,
  child_seat: Baby,
  luggage_space: Luggage,
  extra_luggage: Package,
  roof_carrier: Box,
  water_bottle: Droplets,
  newspaper: BookOpen,
  magazine: BookOpen,
  tissues: Package,
  sanitizer: Sparkles,
  first_aid: Cross,
  clean_cab: Sparkles,
  sanitized_cab: ShieldCheck,
  verified_driver: BadgeCheck,
  trained_driver: Award,
  driver_rating: Star,
  fare_estimate: Banknote,
  transparent_billing: Receipt,
  cashless_payment: CreditCard,
  upi_accepted: Smartphone,
  card_accepted: CreditCard,
  ride_insurance: Shield,
  sos_button: Siren,
  live_tracking: MapPinned,
  share_ride_status: Share2,
  otp_verification: Lock,
  toll_included: CreditCard,
  fuel_included: Fuel,
  driver_contact: Phone,
  support_24x7: Clock,
  instant_booking: Zap,
  free_cancellation: RefreshCw,
  free_waiting: Timer,
  meet_and_greet: HandMetal,
  flight_tracking: Plane,
  multiple_stops: Waypoints,
  pet_friendly: Activity,
  wheelchair_accessible: Accessibility,
  female_driver: Users,
};


export const BikeFeatures: Record<string, LucideIcon> = {
  sports_bike: Bike,
  cruiser: Bike,
  adventure_bike: Bike,
  scooter: Bike,
  electric_bike: BatteryCharging,
  superbike: Zap,
  dirt_bike: Bike,
  touring_bike: Route,
  commuter: Bike,
  cafe_racer: Bike,
  naked_bike: Bike,
  dual_sport: Bike,
  moped: Bike,
  scooty: Bike,
  abs: ShieldCheck,
  disc_brakes: CircleDot,
  tubeless_tyres: CircleGauge,
  led_headlights: Flashlight,
  digital_console: CircleGauge,
  kick_start: Power,
  self_start: Zap,
  alloy_wheels: Settings,
  gear: Settings,
  gearless: Settings,
  fuel_efficient: Fuel,
  high_mileage: Gauge,
  low_maintenance: Wrench,
  powerful_engine: Zap,
  lightweight: Bike,
  heavy_duty: Shield,
  off_road: Mountain,
  city_ride: Building,
  highway_ready: Route,
  long_range: Fuel,
  fast_charging: BatteryCharging,
};

export const BikeAmenities: Record<string, LucideIcon> = {
  helmet: ShieldCheck,
  two_helmets: ShieldCheck,
  riding_gear: Shield,
  gloves: Shield,
  knee_guard: Shield,
  elbow_guard: Shield,
  rain_coat: CloudRain,
  rain_cover: Umbrella,
  phone_mount: Smartphone,
  mobile_holder: Smartphone,
  usb_charger: Plug,
  saddle_bag: Package,
  tank_bag: Box,
  top_box: Box,
  pillion_seat: Users,
  backrest: Armchair,
  leg_guard: Shield,
  crash_guard: ShieldAlert,
  lock: Lock,
  chain_lock: Lock,
  disc_lock: Lock,
  gps_tracker: Navigation2,
  tool_kit: Wrench,
  puncture_kit: Settings,
  spare_key: Key,
  side_stand: Bike,
  roadside_assistance: Phone,
  breakdown_support: Wrench,
  insurance_included: Shield,
  damage_waiver: ShieldCheck,
  unlimited_kms: Route,
  km_limit: Gauge,
  fuel_included: Fuel,
  delivery: Truck,
  home_delivery: Send,
  doorstep_pickup: MapPinned,
  flexible_return: RefreshCw,
  instant_booking: Zap,
  free_cancellation: RefreshCw,
  identity_verification: BadgeCheck,
  security_deposit: CreditCard,
  cashless_payment: CreditCard,
  age_requirement: AlertTriangle,
  license_required: Award,
  sanitized: Sparkles,
  well_maintained: CheckCircle,
  serviced_regularly: Wrench,
  support_24x7: Clock,
};



export const IconsBundle: Record<string, LucideIcon> = {
  // Hotels
  ...FoodAndDrinks,
  ...ConnectivityAndBusiness,
  ...ComfortAndClimate,
  ...RulesAndAccess,
  ...Facilities,
  ...RoomFeatures,
  ...Transport,
  ...Family,
  ...Locations,
  // Tours
  ...TourFeatures,
  ...TourAmenities,
  // Adventures
  ...AdventureFeatures,
  ...AdventureAmenities,
  // Cabs
  ...CabFeatures,
  ...CabAmenities,
  // Bikes
  ...BikeFeatures,
  ...BikeAmenities,
};


export const amenityIconMap: Record<string, LucideIcon> = { ...IconsBundle };